name: CI/CD con Render

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Dar permisos al wrapper de Maven
        run: chmod +x demo-deploy/mvnw

      - name: Construir aplicación
        run: cd demo-deploy && ./mvnw clean package -DskipTests

      - name: Desplegar en Render
        run: curl "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}